### PR TITLE
Fixed flow issues caused by https://github.com/RickLeinecker/Fortuna/pull/131

### LINKED ISSUE #134: Master doesn't pass Flow
**Describe the bug**
Master fails to pass flow.

**To Reproduce**
1. Use 'npm run flow'
2. See error.

**Expected behavior**
Should pass flow.

**Screenshots**
Screenshot (32)
Screenshot (33)
Screenshot (34)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by SecondThread**
**Description**
Master currently is failing flow, which means people can't work on it. This was caused by PR131 being merged when it didn't pass flow. This fixes that.

Resolves #134 

**Type of change**
Check options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Fix or feature that would cause existing functionality to not work as expected
- [ ] This change requires a update in the design document

**Steps to Verify Functionality**
npm run flow:
image

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design document (if applicable)
- [x] My changes generate no new warnings
- [x] Pulled updated master branch (if changed since branch creation) and corrected any conflicts, if any occur.

### CODE REVIEW

File: src/casus/saveCasus.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+//@flow strict
+
+//TODO: get cookies saved on login
+//the cookies don't actually exist at the moment, so waiting on those getting pushed
+//import Cookies from 'universal-cookie';
+
+function saveCasus(): void {
+	console.log('saving...');
```
Comment (SecondThread) [inline src/casus/saveCasus.js:8]: I know this is trash and in general shouldn't be pushed, but I was in the middle of doing this...

**Review by blaiadam — APPROVED** [review]
Looks great, thank you.
