### PR TITLE
invalidate token if logged in twice

### LINKED ISSUE #477: Users can be logged in on two different websites at once.
**Describe the bug**
Isn't the verify route supposed to prevent this?

**To Reproduce**
1. Login.
2. Go to another computer.
3. Login.

**Expected behavior**
Should log the other person out because their JWT is no longer valid, correct?

**Screenshots**
N/A

**Additional context**
If this is good behavior, then close this issue. Although, I believe we didn't want this.

### PR DESCRIPTION
**Pull request by Airor4**
**Description**
Invalidates tokens from older sessions to enforce single user logins.

**Resolves These Issues**
Resolves #477 

**Type of change**
Check options that are relevant.

- [ ] Bug fix (fixes a bug issue)
- [X] New feature (adds functionality)
- [ ] This fix or feature will cause existing functionality to not work as expected. (Please elaborate in Description.)

**Steps to Verify Functionality**
Make a bulleted/numbered list of steps to verify this feature/bugfix. Include screenshots if necessary.
1) Login user
2) make an authenticated api call and see if it is successful (it should be)
3) login in a new window and redo step 2
4) go back to the first login window and try to make an authenticated api call and it should no longer work.

**Final Checklist:**
Go down the list and check them off.

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have performed a self-review of my own code
- [X] My changes pass Flow, build without errors and (if applicable) pass Jest tests.
- [X] This change requires a update in the design document (if applicable)

### CODE REVIEW

**Review by SecondThread — APPROVED** [review]
lgtm

File: src/backend/controllers/userController.js [hunk 1]
```diff
@@ -232,7 +232,8 @@ exports.login = async (req: Request, res: Response) => {
 		const payload = {
 			user: {
 				// Primary key id generated by MongoDB
-				id: user.id
+				id: user.id,
+				issued: Date.now()
```
Comment (Derplime) [inline src/backend/controllers/userController.js:236]: The issue here is that there is the small possibility that the `issued` property here and the `lastLogin` in the user might be _ever so slightly_ off, since they call separate instances of `Date.now()`

So before the logic that checks if you've logged in before to give a tank to the user, do a singular `const now = Date.now()` and then set everything that needs that `Date.now()` to `now`

**Review by Derplime — CHANGES_REQUESTED** [review]
Just a quick nit on this. Other than that it's fine.

**Review by Derplime — APPROVED** [review]

**Comment by Derplime** [comment]
For clarification, the nit is more of a suggestion to keep the issue date of the jwt in line with the lastLogin field.

**Review by element2112 — APPROVED** [review]

**Review by JohnJCordero — APPROVED** [review]

**Review by element2112 — APPROVED** [review]
