### PR TITLE
Set favorite tanks to null after they are challenged

### LINKED ISSUE #424: Favorite tank isn't set to null after being challenged
**Describe the bug**
When a person who set a challenge is challenged, after the match their favorite tank isn't null. Their wager is set to 0, so that is working correctly.

**To Reproduce**
1. Make a wager.
2. Go to another account
3. Challenge the first account.
4. Go back to first account.
5. Go to armory.
6. View that your favorite tank is still wagered at 0. 

**Expected behavior**
Should have favorite tank set to null post match.

**Screenshots**
image

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by SecondThread**
**Description**
Set favoriteTank/favoriteTanks to null after a wager is challenged/accepted

**Resolves These Issues**
Resolves #424 

**Type of change**
Check options that are relevant.

- [x] Bug fix (fixes a bug issue)
- [ ] New feature (adds functionality)
- [ ] This fix or feature will cause existing functionality to not work as expected. (Please elaborate in Description.)

**Steps to Verify Functionality**
Make a bulleted/numbered list of steps to verify this feature/bugfix. Include screenshots if necessary.
After accepting a wager from this user:
image

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code
- [x] My changes pass Flow, build without errors and (if applicable) pass Jest tests.
- [ ] This change requires a update in the design document (if applicable)

### CODE REVIEW

File: src/backend/controllers/battleController.js [hunk 1]
```diff
@@ -205,7 +206,7 @@ exports.prepareMatch3v3 = async (req: Request, res: Response) => {
 				.status(404)
 				.json({ msg: 'Could not find the challenger in DB'});
 		}
-		// Make sure they have enuf for the wager
+		// Make sure they have enough for the wager
```
Comment (Airor4) [inline src/backend/controllers/battleController.js:209]: lets be real the spelling of enough should be enuf

**Review by Airor4 — APPROVED** [review]

File: src/backend/controllers/battleController.js (hunk 1 above)
Comment (blaiadam) [reply src/backend/controllers/battleController.js:209]: lmfao why Baylor
