### PR TITLE
Show tank components being sold

### LINKED ISSUE #405: Marketplace tanks don't show the tank's components.
**Describe the Feature**
The user doesn't know what they are buying. Just a tank's name and its value.

**To Reproduce**
1. Go to marketplace.
2. Make a tank sale.
3. Log into other user.
4. Check tank sale.

**Expected behavior**
We need to display components of the tank.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JorgeVidal29**
**Description**
Tanks are now shown in the marketplace

**Resolves These Issues**
Resolves #405 

**Type of change**
Check options that are relevant.

- [ ] Bug fix (fixes a bug issue)
- [x] New feature (adds functionality)
- [ ] This fix or feature will cause existing functionality to not work as expected. (Please elaborate in Description.)

**Steps to Verify Functionality**
Made sure to have a tank in the marketplace
Went to marketplace
Saw the tanks that are being sold displayed

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code
- [x] My changes pass Flow, build without errors and (if applicable) pass Jest tests.
- [ ] This change requires a update in the design document (if applicable)

### CODE REVIEW

File: src/marketplace/ListingsView.js [hunk 1]
```diff
@@ -78,6 +83,10 @@ class ListingsView extends React.Component<Props, State> {
 	getMarketSalesForTanks(): void  {
 		getMarketTanks(this.state.userId, sales => {
 				this.setState({itemsForSale: sales.filter(sale => !(allComponents.includes(sale.name)))}); 
+				//Once we have all of the tanks being sold add them to the array that is going to house those tanks
+				for(let i = 0; i < sales.length; i++) {
```
Comment (blaiadam) [inline src/marketplace/ListingsView.js]: When you have a lot of tanks in the marketplace, you will be updating the state a ton. Change this to create an array of Tanks first, and then set the state.

**Review by blaiadam — CHANGES_REQUESTED** [review]
Looks good. I have one change requested, fix that and I'll approve.

File: src/globalComponents/apiCalls/marketPlaceAPIConnections.js [hunk 2]
```diff
@@ -68,7 +68,8 @@ function getMarketSales(userId: string, onLoad:(sales: Array<SaleObject>) => voi
 						sale.salePrice,
 						sale.amount,
 						sale.sellerId,
-						sale._id
+						sale._id,
+						"0"
```
Comment (SecondThread) [inline src/globalComponents/apiCalls/marketPlaceAPIConnections.js]: In JS single quotes are preferred according to our style guide.

Also, this should probably be an empty string

File: src/globalComponents/typesAndClasses/SaleObject.js [hunk 3]
```diff
@@ -6,13 +6,15 @@ class SaleObject {
 	amount: number;
 	sellerId: string;
 	saleId: string;
+	tankId: string;
```
Comment (SecondThread) [inline src/globalComponents/typesAndClasses/SaleObject.js]: If sale objects are also used for item sales, then this should definitely be nullable. Otherwise you have a very confusing sentinel value...

File: src/globalComponents/apiCalls/marketPlaceAPIConnections.js (hunk 2 above)
Comment (SecondThread) [reply src/globalComponents/apiCalls/marketPlaceAPIConnections.js]: On second thought, it should definitely be null, not empty string. I didn't fully read what this was being used for.

File: src/marketplace/ListingsView.js [hunk 4]
```diff
@@ -77,7 +82,17 @@ class ListingsView extends React.Component<Props, State> {
...
+				//Once we have all of the tanks being sold add them to the array that is going to house those tanks
+				const tanksForSale: Array<Tank> = [];
+				for(const tank of sales) {
+					getTankById(tank.tankId, tankReturned => {
+						tanksForSale.push(tankReturned);
+					});
+				}
+				this.setState({
+					itemsForSale: sales.filter(sale => !(allComponents.includes(sale.name))),
+					tanksBeingShown: tanksForSale
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: I talked to Adam about this, but this is very confusing and probably doesn't do what you want it to in some cases. This array isn't actually full yet, so you are about to call render without the stuff you need in this array, and then it will get put into the array after the fact

Comment (SecondThread) [reply src/marketplace/ListingsView.js]: The solution is to not call setstate until after the API call you are waiting for returns

**Review by SecondThread — CHANGES_REQUESTED** [review]

File: src/globalComponents/apiCalls/tankAPIIntegration.js [hunk 5]
```diff
@@ -203,13 +203,52 @@ function deleteTank(tankId: string, onLoad:() => void): void {
 	);
 }
 
+//Input: Id of a tank
+//Output: a tank object of the tank whose id equals the id that was passed in
+function getTankById(tankId: ?string, onLoad:(tank: Tank) => void): void {
+	if(tankId == null) {
```
Comment (SecondThread) [inline src/globalComponents/apiCalls/tankAPIIntegration.js]: If this method doesn't allow tankId to be null, tankId shouldn't be nullable, and you don't need this if statement. Wherever you call this method, you need to be careful that you don't pass null into it.

File: src/marketplace/ShowTankPopup.js [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+	tankBeingShown: Tank
+|}
+
+// This popup takes an id of a tank, gets that tank, and shows it
+class ShowTankPopup extends React.Component<Props, State> {
+
+	constructor(props: Props) {
+		super(props);
+		//This blank tank is a placeholder for the tank that we are goiing to pull from the show tank function
+		const blankTank: BackendTank = new BackendTank(
```
Comment (SecondThread) [inline src/marketplace/ShowTankPopup.js]: This is very sketchy. Instead of using sentinel values, you should make tankBeingShown nullable.

**Review by blaiadam — APPROVED** [review]
Looks good

File: src/marketplace/ListingsView.js [hunk 7]
```diff
@@ -86,21 +87,38 @@ class ListingsView extends React.Component<Props, State> {
...
+			// Handle tank and components different to display tank 
+			// Have to make sure that the tanks are being ready to be shown
+			if(this.props.sellerType === 'tanks') {
+				cards.push(
+					<div className="card mb-2" key={i}>
+						<div className="card-body">
+							<h5 className="card-title">Item to buy: {toTitleCase(this.state.itemsForSale[i].name)}</h5>
+							<h5 className="card-title">Price: ${this.state.itemsForSale[i].price}</h5>
+							<h5 className="card-title">Quantity: {this.state.itemsForSale[i].amount}</h5>
+							<ShowTankPopup tankIdToShow={this.state.itemsForSale[i].tankId}></ShowTankPopup>
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: You can do something like:
```
const tankIdForItem = this.state.itemsForSale[i].tankId;
if (tankIdForItem == null) {
  throw new Error('something describing why this is illegal');
}
```
above the JSX.
Then you don't need to make ShowTankPopup.props.tankIdToShow nullable. (It doesn't make sense to me at least for it to be nullable because it doesn't make sense to show a tank with null as its id)

File: src/marketplace/ListingsView.js [hunk 8]
```diff
@@ -86,21 +87,38 @@ class ListingsView extends React.Component<Props, State> {
...
+							<button className="btn btn-success mt-2" onClick={() => this.buyItem(this.state.itemsForSale[i].sellerId, this.state.itemsForSale[i].saleId)}>Buy</button>
+						</div>
 					</div>
-				</div>
-			)
+				)
+			}
+			else if(this.props.sellerType !== 'tanks') {
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: uh, isn't that what 'else' means?

if (x) 
  ...
else if (!x)
  ...
??

File: src/marketplace/ShowTankPopup.js [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+			<div>
+				<button className="btn mt-2" onClick={() => this.showTank()}>
+					See Tank
+				</button>
+				<Popup 
+					open={this.state.showingTank}
+					onClose={() => this.handleCloseClick()}
+				>
+					<div className="popup">
+						<TankDisplay tankToDisplay={this.state.tankBeingShown} smallTank={false} />
```
Comment (SecondThread) [inline src/marketplace/ShowTankPopup.js]: If, after you make the above changes, you are about to get a flow error saying that this.state.tankBeingShown can be null, but tankToDisplay can't be, then you can check if it is null, and if it is show like the text "loading tank..." instead for instance

**Review by SecondThread — CHANGES_REQUESTED** [review]
Pretty small stuff, but I would like if you could fix it before pushing

File: src/globalComponents/apiCalls/tankAPIIntegration.js (hunk 5 above)
Comment (JorgeVidal29) [reply src/globalComponents/apiCalls/tankAPIIntegration.js]: If we don't do that flow gives that error we talked about

Comment (JorgeVidal29) [reply src/globalComponents/apiCalls/tankAPIIntegration.js]: Fixing the below fixed this

File: src/marketplace/ListingsView.js [hunk 10]
```diff
@@ -86,21 +87,44 @@ class ListingsView extends React.Component<Props, State> {
...
-						<h5 className="card-title">Item to buy: {toTitleCase(this.state.itemsForSale[i].name)}</h5>
-						<h5 className="card-title">Price: ${this.state.itemsForSale[i].price}</h5>
-						<h5 className="card-title">Quantity: {this.state.itemsForSale[i].amount}</h5>
-						<button className="btn btn-success mt-2" onClick={() => this.buyItem(this.state.itemsForSale[i].sellerId, this.state.itemsForSale[i].saleId)}>Buy</button>
+			// Handle tank and components different to display tank 
+			// Have to make sure that the tanks are being ready to be shown
+			if(this.props.sellerType === 'tanks') {
+				const tankId = this.state.itemsForSale[i].tankId;
+				if(tankId == null) {
+					console.log("Tank Id is null");
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: You should throw an error here so that we notice

File: src/marketplace/ListingsView.js [hunk 11]
```diff
@@ -86,21 +87,44 @@ class ListingsView extends React.Component<Props, State> {
...
+				}
+				else {
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: Dont need the else if we are crashing in the if statement

File: src/marketplace/ListingsView.js [hunk 12]
```diff
@@ -86,21 +87,44 @@ class ListingsView extends React.Component<Props, State> {
...
+						<div className="card-body">
+							<h5 className="card-title">Item to buy: {toTitleCase(this.state.itemsForSale[i].name)}</h5>
+							<h5 className="card-title">Price: ${this.state.itemsForSale[i].price}</h5>
+							<h5 className="card-title">Quantity: {this.state.itemsForSale[i].amount}</h5>
+							<button className="btn btn-success mt-2" onClick={() => this.buyItem(this.state.itemsForSale[i].sellerId, this.state.itemsForSale[i].saleId)}>Buy</button>
+						</div>
 					</div>
-				</div>
-			)
+				)
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: semicolon please

File: src/marketplace/ListingsView.js [hunk 13]
```diff
@@ -86,21 +87,44 @@ class ListingsView extends React.Component<Props, State> {
...
+						<div className="card mb-2" key={i}>
+							<div className="card-body">
+								<h5 className="card-title">Tank to buy: {toTitleCase(this.state.itemsForSale[i].name)}</h5>
+								<h5 className="card-title">Price: ${this.state.itemsForSale[i].price}</h5>
+								<h5 className="card-title">Quantity: {this.state.itemsForSale[i].amount}</h5>
+								<ShowTankPopup tankIdToShow={tankId}></ShowTankPopup>
+								<button className="btn btn-success mt-2" onClick={() => this.buyItem(this.state.itemsForSale[i].sellerId, this.state.itemsForSale[i].saleId)}>Buy</button>
+							</div>
+						</div>
+					)
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: semicolon please

**Review by SecondThread — APPROVED** [review]
Please fix suggestions before pushing
