### PR TITLE
2 New Components and CSS Architecture Fix

### LINKED ISSUE #67: Fix CSS Architecture
**Describe the bug**
The way we are rendering our pages, if you have a local CSS file overwriting a part in the Main.css file, it will overwrite it in all pages.
To better explain, Login.css changes will also affect the Main Menu page.

**To Reproduce**
1. Go to src folder.
2. Edit the Login.css file.
3. Changes should spread to all pages.

**Expected behavior**
Local CSS files should take priority to the Main.css.

### PR DESCRIPTION
**Pull request by blaiadam**
**Description**
This PR fixes bugs and implements features.

The bug it fixes is that the local CSS files were not functioning as planned, so I merged the local CSS files into one (Main.css). Although, if we find a better way to handle this issue, I am not opposed to changing it. Also, fixes overlapping button issue.

The features this implements is the Navbar and Leaderboard components have been fully implemented. The comments in the components JavaScript files provide a detailed explanation on how to call them. Also, Main Menu and Battle Arena have their UI updated to meet current standards.

Fixes #67 #64 #66 #69 #70 

**Type of change**
Check options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Fix or feature that would cause existing functionality to not work as expected
- [x] This change requires a update in the design document

**Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the design document (if applicable)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/Navbar.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+// Prop names:
+// styleName (takes the CSS style for the back button, two options are navbtn and nobtn)
+// returnName (takes text for describing the back button)
+// pageName (takes a title for top of the page)
+// userName (takes user's name and currency)
+//
+// EXAMPLE PROP USAGE = <Navbar styleName="navbtn" returnName="Back to Main Menu" pageName="Armory" userName="FRIcker | $465128"/>
+//
+// Right column needs to be updated to have the logged in user's name and current currency passed to it.
+class Navbar extends React.Component<Props> {
```
Comment (SecondThread) [inline src/components/Navbar.js:32]: You have to define what the type of Props are. e.g. type Props = {styleName: string, returnName: string, pageName: string, userName: string}

File: src/components/Navbar.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+	render(): React.Node {
+		return (
+			<div className="navbar">
+				<div className="navleft">
+					<Link to={this.props.linkName}>
```
Comment (SecondThread) [inline src/components/Navbar.js:38]: If you are using a field like 'linkName' then you have to define it in a type so you are sure that it exists. It might be null and crash/not work.

File: src/mainmenu/MainMenu.js [hunk 3]
```diff
@@ -2,48 +2,33 @@
...
 			<div id="Parent">
-				<div className="row styleForRow">
-					<div className="col-md-4">
-						<Link to="/Login">
-							<button type="button" className="btn btn-secondary btn-lg">&lt;- Back to Login</button>
-						</Link>
-					</div>
-					<h1 className="col-md-4 text-center">Main Menu</h1>
+				<Navbar styleName="navbtn" linkName="/Login" returnName="Back to Login" pageName="Main Menu" userName="FRIcker | $465128"/>
+				<h1 className="menuheader">Where to Commander?</h1>
```
Comment (SecondThread) [inline src/mainmenu/MainMenu.js:14]: I like it lol

File: src/components/Leaderboard.js [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+
+// Leaderboard component. Displays top 10 players. The props takes a list of 10 players.
+// 
+// Prop Names:
+// leaderNames (Pass the list of 10 top players to display on the leaderboard)
+// 
+// EXAMPLE PROP USAGE = '<Leaderboard leaderNames={ ["John", "Bill", "Suck", "Big Suck", "HEhaw", "XXXXXfweckerXXXXX", "Yes", "2more", "9", "10haha"] } />'
+//
+// Needs to be updated to pass actual Users to it.
+class Leaderboard extends React.Component<Props> {
```
Comment (SecondThread) [inline src/components/Leaderboard.js:17]: Again, props need to be defined.
Here is a working example: https://github.com/RickLeinecker/Fortuna/blob/master/src/casus/blockBank/BlockBank.js

File: src/components/Navbar.js (hunk 1 above)
Comment (SecondThread) [reply src/components/Navbar.js:32]: Example: https://github.com/RickLeinecker/Fortuna/blob/master/src/casus/blockBank/BlockBank.js

**Review by SecondThread — CHANGES_REQUESTED** [review]
Fails flow: Props type is not defined

File: src/components/Navbar.js (hunk 1 above)
Comment (blaiadam) [reply src/components/Navbar.js:32]: I'll fix this soon. First, I need to fix my Flow. Almost forgot about that.

**Comment by Derplime** [comment]
@blaiadam
Just a heads up that with merging Baylor's PR there's a conflict here with the `Login.css` file, as well as any changes asked by David.

File: src/components/Navbar.js (hunk 2 above)
Comment (blaiadam) [reply src/components/Navbar.js:38]: The LinkType has been created and implemented.

File: src/components/Navbar.js (hunk 1 above)
Comment (blaiadam) [reply src/components/Navbar.js:32]: Props have been created in both components.

File: src/components/Leaderboard.js (hunk 4 above)
Comment (blaiadam) [reply src/components/Leaderboard.js:17]: Props have been created in both components.

File: src/components/Leaderboard.js [hunk 5]
```diff
@@ -0,0 +1,37 @@
+//@flow strict
+
+import * as React from 'react';
+
+type Props = {
```
Comment (SecondThread) [inline src/components/Leaderboard.js:5]: nit: make these closed. (i. e. use vertical bars around them, as specified in the design doc)

File: src/components/Navbar.js [hunk 6]
```diff
@@ -0,0 +1,53 @@
+//@flow strict
+
+import * as React from 'react';
+import { Link } from 'react-router-dom';
+
+import type {LinkType} from './LinkType.js';
+
+type Props = {
+	styleName: string,
```
Comment (SecondThread) [inline src/components/Navbar.js:9]: This shouldn't be string. It should be 'nobtn'|'navbar' or whatever the legal styles are. Someone like me who doesn't know what this is used for is likely to pass in the wrong string if we want to use it.

**Review by SecondThread — APPROVED** [review]
Mostly looks good, just a few nit picks
