### PR TITLE
No more API calls when switching listings

### LINKED ISSUE #474: Going from a component view to tank view in Marketplace leads to a white screen.
**Describe the bug**
Read title.

**To Reproduce**
1. Go to Marketplace.
2. Click any of the component listings.
3. Click the tank listings.
4. View white screen.

**Expected behavior**
Should load the tanks correctly.

**Screenshots**
image

**Additional context**
N/A

### LINKED ISSUE #507: Marketplace crashes when a user sells their last component
**Describe the bug**
When selling the last component a user owns, the website will whitescreen.

**To Reproduce**
1. Sell all your components.

**Expected behavior**
Shouldn't crash.

**Screenshots**
image

**Additional context**
Might need to make a special case for if the components go to empty.

### PR DESCRIPTION
**Pull request by blaiadam**
**Description**
In Marketplace, we were making an API call and filtering all of the sales every time a user clicked a new listings view type. Now, it will get all of the market sales and split them up on the front end. Then, it will swap them out when a new listings view type is clicked. This PR should drastically speed up marketplace, as well as prevent crashes from swapping between types.

The Casus editor CSS change does not alter anything. The master listings header has been updated as well. Also, I fixed the crash on selling last component.

**Resolves These Issues**
Resolves #474 
Resolves #507 

**Type of change**
Check options that are relevant.

- [x] Bug fix (fixes a bug issue)
- [ ] New feature (adds functionality)
- [ ] This fix or feature will cause existing functionality to not work as expected. (Please elaborate in Description.)

**Steps to Verify Functionality**
1. Make sure marketplace has tank sales and component sales.
2. Rapidly switch between them to make sure no crashes occur.
3. Purchase items to ensure that purchasing is still functioning as intended.

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code
- [x] My changes pass Flow, build without errors and (if applicable) pass Jest tests.
- [ ] This change requires a update in the design document (if applicable)

### CODE REVIEW

File: src/marketplace/ListingsView.js [hunk 1]
```diff
@@ -11,19 +11,25 @@ import { allComponents } from '../globalComponents/typesAndClasses/TankComponent
...
+	scannersForSale: Array<SaleObject>,
+	scannerAddonsForSale: Array<SaleObject>,
+	jammersForSale: Array<SaleObject>,
+	treadsForSale: Array<SaleObject>,
 	itemsForSale: Array<SaleObject>,
-	// This is used to hold all of the tanks for sale. Will be null when the sellerType is not tank
-	tanksForSale: ?Array<Tank>
+	tanksForSale: Array<SaleObject>,
+	tanks: Array<Tank>,
+	cards: Array<React.Element<'div'>>
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: I haven't read everything yet, but this is almost always an indication that we are doing something wrong. We don't want to be storing how we are rendering something, we want to be storing the data that we are rendering, and then we can compute how to render it in the render() method

File: src/marketplace/ListingsView.js [hunk 2]
```diff
@@ -32,117 +38,171 @@ class ListingsView extends React.Component<Props, State> {
...
 	}
 
-	// Once mounted, get the user's ID.
-	componentDidMount() {
-		this.getUserId();
+	// Once mounted, get the user's ID and set the sales.
+	componentDidMount(): void {
+		getUserAPICall(user => {
+			this.setState({userId: user.userId});
+			this.getSales();
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: getSales looks at this.state.userId, so shouldn't this be:
`setState({userId: user.userId}, this.getSales);`?

File: src/marketplace/ListingsView.js [hunk 3]
```diff
@@ -32,117 +38,171 @@ class ListingsView extends React.Component<Props, State> {
...
-	// Else it directs it to getMarketSalesForComponents()
-	directSaleToProperFunction(): void {
-		if(this.props.sellerType === 'tanks') {
-			this.getMarketSalesForTanks();
-		}
-		else {
-			this.getMarketSalesForComponents();
+		if (prevProps !== this.props) {
+			switch (this.props.sellerType) {
+				case 'chassis':
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: Creating these cards should be done in the render method and they shouldn't be stored inside the component's state

File: src/marketplace/ListingsView.js [hunk 4]
```diff
@@ -32,117 +38,171 @@ class ListingsView extends React.Component<Props, State> {
...
+			});
 
-	//This function uses the users id and gets the tanks that are active in the marketplace
-	getMarketSalesForTanks(): void  {
-		getMarketTanks(this.state.userId, sales => {
-				this.setState({itemsForSale: sales.filter(sale => !(allComponents.includes(sale.name)))}); 
-				this.getTanksToShow();
+			// After getting the sales, reset the cards according to the sellerType.
+			switch (this.props.sellerType) {
+				case 'chassis':
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: ditto earlier, and also this is a lot of unnecessarily duplicated code

File: src/marketplace/ListingsView.js [hunk 5]
```diff
@@ -32,117 +38,171 @@ class ListingsView extends React.Component<Props, State> {
...
 
-	//This function uses tanks id from the state , creates those tanks , and adds them to the array of tanks
-	getTanksToShow() { 
-		const arrayOfTankIds = [];
-		for(let i = 0; i < this.state.itemsForSale.length; i++) {
-			if(this.state.itemsForSale[i].tankId == null) {
+	// Converts SaleObject to Tank.
+	convertSalesToTanks(saleTanks: Array<SaleObject>): void {
+		// Do not convert if there are no tanks to convert.
+		if (saleTanks.length === 0) {
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: why do we need this special case? If our code doesn't work when there are no tanks to convert it seems like we have messy logic somewhere...

File: src/marketplace/ListingsView.js [hunk 6]
```diff
@@ -32,117 +38,171 @@ class ListingsView extends React.Component<Props, State> {
...
 		});
 	}
 
-	// This creates a card for every sale
-	createCards = () => {
-		const cards = []
-		//Check for no sales
-		if(this.state.itemsForSale.length === 0) {
-			return(<h5>No Sales Availiable At This Time</h5>);
+	createCards = (itemsForSale: Array<SaleObject>, saleType: MarketplaceViewType): Array<React.Element<'div'>> => {
```
Comment (SecondThread) [inline src/marketplace/ListingsView.js]: This method should only ever be called from render()

File: src/marketplace/Marketplace.js [hunk 7]
```diff
@@ -23,57 +23,59 @@ class Marketplace extends React.Component<Props, State> {
 	constructor() {
 		super();
 		verifyLogin();
-		this.state={
-			marketplaceViewClicked: 'NONE'
+		this.state = {
+			marketplaceViewClicked: null
```
Comment (SecondThread) [inline src/marketplace/Marketplace.js:27]: thanks

**Review by SecondThread — CHANGES_REQUESTED** [review]
The big change I am requesting is that this is storing the _way_ that things are being rendered in the state, instead of storing _what_ is being rendered. This leads to duplicated code, states that could be illegal (if how it is being rendered doesn't match what is being rendered), and confusion when other people try to understand what is going on.

File: src/marketplace/ListingsView.js (hunk 2 above)
Comment (blaiadam) [reply src/marketplace/ListingsView.js]: Good catch.

File: src/marketplace/ListingsView.js (hunk 3 above)
Comment (blaiadam) [reply src/marketplace/ListingsView.js]: Once I am back, I will change it to map the cards out inside the render method instead. It might take me a bit to change stuff around to make it work, but it can't be too hard.

**Review by JorgeVidal29 — APPROVED** [review]
Passed flow, was able to see listings, and was able to buy and sell items. Looks good to me

**Review by SecondThread — APPROVED** [review]
Looks good, thanks for changing
