### PR TITLE
Showing all of tanks for sale

### LINKED ISSUE #475: Show tanks without clicking button
**Describe the bug**
When wanting to see a tank in the marketplace, the user must click a button, we would like for the tank to display where the button currently is.

**To Reproduce**
1. Go to the Marketplace
2. See the button and no tanks

**Expected behavior**
Expect to see the tanks

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by JorgeVidal29**
**Description**
The marketplace now shows the tanks without the need for clicking a button to see the tanks

**Resolves These Issues**
Resolves #475 

**Type of change**
Check options that are relevant.

- [x] Bug fix (fixes a bug issue)
- [ ] New feature (adds functionality)
- [ ] This fix or feature will cause existing functionality to not work as expected. (Please elaborate in Description.)

**Steps to Verify Functionality**
Went to the marketplace
Saw the tanks being displayed

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code
- [x] My changes pass Flow, build without errors and (if applicable) pass Jest tests.
- [ ] This change requires a update in the design document (if applicable)

### CODE REVIEW

File: src/backend/controllers/tankController.js [hunk 1]
```diff
@@ -561,20 +561,26 @@ exports.getTankById = async (req: Request, res: Response) => {
 	}
```
Comment (Derplime) [inline src/backend/controllers/tankController.js:561]: Currently nothing will be used here for express validation if you don't even have the use of the express validation in the route. As of now, this above code is dead code.

File: src/backend/routes/tankRoutes.js [hunk 2]
```diff
@@ -116,8 +116,6 @@ router.get('/getBotTanks', tankController.getBotTanks);
 // Route call: /getTankById/<tankId>
 // Body: N/A
 // returns the tank object
-router.get('/getTankById/:tankId', [
-	check('tankId', 'a valid MongoId is required.').isMongoId()
-], tankController.getTankById);
+router.get('/getTanksById', tankController.getTankById);
```
Comment (Derplime) [inline src/backend/routes/tankRoutes.js]: Seeing that there is a use of the query parameters, should you not use the express validator here? What is expected to go here? It seems like its supposed to be taking something in. Otherwise you can give this thing random stuff. Also it seems that this has been edited to the point that the comment to describe this route should be updated.

File: src/marketplace/ShowTankPopup.js [hunk 3]
```diff
@@ -61,4 +61,4 @@ class ShowTankPopup extends React.Component<Props, State> {
 	}
 }
 
-export default ShowTankPopup;
\ No newline at end of file
+export default ShowTankPopup;*/
```
Comment (Derplime) [inline src/marketplace/ShowTankPopup.js]: Why is this whole file commented out? This is baffling. If this file is not needed why keep it here?

**Review by Derplime — CHANGES_REQUESTED** [review]
I left some comments. Hopefully I can get clarity on them, but they're questions that block merging this in for me.

File: src/marketplace/ShowTankPopup.js (hunk 3 above)
Comment (JorgeVidal29) [reply src/marketplace/ShowTankPopup.js]: Sorry i thought i had deleted this file.

File: src/backend/routes/tankRoutes.js [hunk 4]
```diff
@@ -112,12 +112,13 @@ router.delete('/deleteTank/:tankId', [
...
+// Retrieve tank objects
 // Route call: /getTankById/<tankId>
 // Body: N/A
-// returns the tank object
-router.get('/getTankById/:tankId', [
-	check('tankId', 'a valid MongoId is required.').isMongoId()
+// Takes an array of tank ids
+// returns the tank objects
+router.get('/getTanksById', [
+	check('array', 'a valid MongoId is required.').isArray()
```
Comment (Derplime) [inline src/backend/routes/tankRoutes.js]: Should it be `An array of MongoIds is required`? Other than that it's good.

**Review by Derplime — CHANGES_REQUESTED** [review]
One nit on the validator message then you're good

File: src/backend/routes/tankRoutes.js (hunk 4 above)
Comment (Airor4) [reply src/backend/routes/tankRoutes.js]: yah can i chain it like isArray().isMongoId()?

**Review by Derplime — APPROVED** [review]
Alright you're good
