### PR TITLE
Better rounding and truncating

### LINKED ISSUE #81: Rounding a rediculously large double to an int might take an obscene amout of time
**Describe the bug**
If you have a double value that is rediculously big (order of magnitide of 1e100, for example) and then call round() on it, the interpriter will run forever. Well, techinically it will end eventually, but obviously this should run in O(1), instead of O(doubleValue/2^32) time.

**To Reproduce**
round a massive double to an int

### PR DESCRIPTION
**Pull request by SecondThread**
**Description**
Made rounding run in a reasonable amount of time. It turned out to be pretty easy, but now that we can run code it was easy enough to make sure that it worked as expected.

**Resolves These Issues**
Resolves #81 

**Type of change**
Check options that are relevant.

- [x] Bug fix (fixes a bug issue)
- [ ] New feature (adds functionality)
- [ ] This fix or feature will cause existing functionality to not work as expected. (Please elaborate in Description.)

**Steps to Verify Functionality**
Make a bulleted/numbered list of steps to verify this feature/bugfix. Include screenshots if necessary.
Same output as before:
image

Code that prints that:
image

Passes flow:
image

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my own code
- [x] My changes pass Flow, build without errors and (if applicable) pass Jest tests.
- [ ] This change requires a update in the design document (if applicable)

### CODE REVIEW

**Comment by SecondThread** [comment]
This code also doesn't take forever to run:
image

File: src/casus/interpreter/IntValue.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ class IntValue {
 		//validate that this number is in the range [-2^31, 2^31), and put it in there if it isn't
 		const minValue=-(2**31), maxValue=-minValue-1;
 		const modSize=2**32;
-		let x=input;
+		let x=input%modSize;
```
Comment (blaiadam) [inline src/casus/interpreter/IntValue.js:100]: lol, that's great

**Review by blaiadam — APPROVED** [review]
Passes flow and doesn't crash. Great job.
